/* To avoid CSS expressions while still supporting IE 7 and IE 6, use this script */
/* The script tag referencing this file must be placed before the ending body tag. */

/* Use conditional comments in order to target IE 7 and older:
	<!--[if lt IE 8]><!-->
	<script src="ie7/ie7.js"></script>
	<!--<![endif]-->
*/

(function() {
	function addIcon(el, entity) {
		var html = el.innerHTML;
		el.innerHTML = '<span style="font-family: \'gicon\'">' + entity + '</span>' + html;
	}
	var icons = {
		'gi-file-text': '&#xe900;',
		'gi-file-text2': '&#xe901;',
		'gi-files-text': '&#xe902;',
		'gi-files-text2': '&#xe903;',
		'gi-picture': '&#xe904;',
		'gi-picture2': '&#xe905;',
		'gi-book': '&#xe906;',
		'gi-book2': '&#xe907;',
		'gi-clipboard': '&#xe908;',
		'gi-clipboard2': '&#xe909;',
		'gi-paperclip': '&#xe90a;',
		'gi-paperclip2': '&#xe90b;',
		'gi-folder': '&#xe90c;',
		'gi-folder2': '&#xe90d;',
		'gi-stats': '&#xe90e;',
		'gi-stats2': '&#xe90f;',
		'gi-pie-chart': '&#xe910;',
		'gi-pie-chart2': '&#xe911;',
		'gi-printer': '&#xe912;',
		'gi-printer2': '&#xe913;',
		'gi-briefcase': '&#xe914;',
		'gi-briefcase2': '&#xe915;',
		'gi-trash': '&#xe916;',
		'gi-trash2': '&#xe917;',
		'gi-sort-down': '&#xe918;',
		'gi-sort-down2': '&#xe919;',
		'gi-sort-up': '&#xe91a;',
		'gi-sort-up2': '&#xe91b;',
		'gi-list': '&#xe91c;',
		'gi-list2': '&#xe91d;',
		'gi-bubble': '&#xe91e;',
		'gi-bubble2': '&#xe91f;',
		'gi-bubble-text': '&#xe920;',
		'gi-bubble-text2': '&#xe921;',
		'gi-bubble-dots': '&#xe922;',
		'gi-bubble-dots2': '&#xe923;',
		'gi-bubbles': '&#xe924;',
		'gi-bubbles2': '&#xe925;',
		'gi-bubble3': '&#xe926;',
		'gi-bubble4': '&#xe927;',
		'gi-bubble5': '&#xe928;',
		'gi-bubble6': '&#xe929;',
		'gi-mail': '&#xe92a;',
		'gi-mail2': '&#xe92b;',
		'gi-letter': '&#xe92c;',
		'gi-letter2': '&#xe92d;',
		'gi-mail-open': '&#xe92e;',
		'gi-mail-open2': '&#xe92f;',
		'gi-paperclip3': '&#xe930;',
		'gi-paperclip4': '&#xe931;',
		'gi-user-menu': '&#xe932;',
		'gi-user-menu2': '&#xe933;',
		'gi-lock-opened': '&#xe934;',
		'gi-lock-opened2': '&#xe935;',
		'gi-lock': '&#xe936;',
		'gi-lock2': '&#xe937;',
		'gi-wrench': '&#xe938;',
		'gi-wrench2': '&#xe939;',
		'gi-gear': '&#xe93a;',
		'gi-gear2': '&#xe93b;',
		'gi-equalizer': '&#xe93c;',
		'gi-equalizer2': '&#xe93d;',
		'gi-compass': '&#xe93e;',
		'gi-compass2': '&#xe93f;',
		'gi-hourglass': '&#xe940;',
		'gi-hourglass2': '&#xe941;',
		'gi-location': '&#xe942;',
		'gi-location2': '&#xe943;',
		'gi-map': '&#xe944;',
		'gi-map2': '&#xe945;',
		'gi-trophy': '&#xe946;',
		'gi-trophy2': '&#xe947;',
		'gi-badge': '&#xe948;',
		'gi-badge2': '&#xe949;',
		'gi-photo': '&#xe94a;',
		'gi-photo2': '&#xe94b;',
		'gi-tablet': '&#xe94c;',
		'gi-tablet2': '&#xe94d;',
		'gi-screen': '&#xe94e;',
		'gi-screen2': '&#xe94f;',
		'gi-floppy': '&#xe950;',
		'gi-floppy2': '&#xe951;',
		'gi-list3': '&#xe952;',
		'gi-list4': '&#xe953;',
		'gi-sphere': '&#xe954;',
		'gi-sphere2': '&#xe955;',
		'gi-window': '&#xe956;',
		'gi-window2': '&#xe957;',
		'gi-star': '&#xe958;',
		'gi-star2': '&#xe959;',
		'gi-bell': '&#xe95a;',
		'gi-bell2': '&#xe95b;',
		'gi-bell3': '&#xe95c;',
		'gi-bell4': '&#xe95d;',
		'gi-icons': '&#xe95e;',
		'gi-icons2': '&#xe95f;',
		'gi-icons3': '&#xe960;',
		'gi-icons4': '&#xe961;',
		'gi-square-arrow-left': '&#xe962;',
		'gi-square-arrow-left2': '&#xe963;',
		'gi-square-arrow-right': '&#xe964;',
		'gi-square-arrow-right2': '&#xe965;',
		'gi-square-arrow-up': '&#xe966;',
		'gi-square-arrow-up2': '&#xe967;',
		'gi-square-arrow-down': '&#xe968;',
		'gi-square-arrow-down2': '&#xe969;',
		'gi-square-plus': '&#xe96a;',
		'gi-square-plus2': '&#xe96b;',
		'gi-square-minus': '&#xe96c;',
		'gi-square-minus2': '&#xe96d;',
		'gi-square-cancel': '&#xe96e;',
		'gi-square-cancel2': '&#xe96f;',
		'gi-square-checkmark': '&#xe970;',
		'gi-square-checkmark2': '&#xe971;',
		'gi-plus': '&#xe972;',
		'gi-plus2': '&#xe973;',
		'gi-minus': '&#xe974;',
		'gi-minus2': '&#xe975;',
		'gi-cancel': '&#xe976;',
		'gi-cancel2': '&#xe977;',
		'gi-checkmark': '&#xe978;',
		'gi-checkmark2': '&#xe979;',
		'gi-circle-chevron-left': '&#xe97a;',
		'gi-circle-chevron-left2': '&#xe97b;',
		'gi-circle-chevron-right': '&#xe97c;',
		'gi-circle-chevron-right2': '&#xe97d;',
		'gi-circle-chevron-up': '&#xe97e;',
		'gi-circle-chevron-up2': '&#xe97f;',
		'gi-circle-chevron-down': '&#xe980;',
		'gi-circle-chevron-down2': '&#xe981;',
		'gi-circle-arrow-left': '&#xe982;',
		'gi-circle-arrow-left2': '&#xe983;',
		'gi-circle-arrow-right': '&#xe984;',
		'gi-circle-arrow-right2': '&#xe985;',
		'gi-circle-arrow-up': '&#xe986;',
		'gi-circle-arrow-up2': '&#xe987;',
		'gi-circle-arrow-down': '&#xe988;',
		'gi-circle-arrow-down2': '&#xe989;',
		'gi-circle-plus': '&#xe98a;',
		'gi-circle-plus2': '&#xe98b;',
		'gi-circle-minus': '&#xe98c;',
		'gi-circle-minus2': '&#xe98d;',
		'gi-circle-cancel': '&#xe98e;',
		'gi-circle-cancel2': '&#xe98f;',
		'gi-circle-checkmark': '&#xe990;',
		'gi-circle-checkmark2': '&#xe991;',
		'gi-arrow-ccw': '&#xe992;',
		'gi-arrow-ccw2': '&#xe993;',
		'gi-sync': '&#xe994;',
		'gi-sync2': '&#xe995;',
		'gi-magnifier': '&#xe996;',
		'gi-magnifier2': '&#xe997;',
		'gi-zoom-in': '&#xe998;',
		'gi-zoom-in2': '&#xe999;',
		'gi-zoom-out': '&#xe99a;',
		'gi-zoom-out2': '&#xe99b;',
		'gi-cloud-download': '&#xe99c;',
		'gi-cloud-download2': '&#xe99d;',
		'gi-cloud-upload': '&#xe99e;',
		'gi-cloud-upload2': '&#xe99f;',
		'gi-delete': '&#xe9a0;',
		'gi-delete2': '&#xe9a1;',
		'gi-label': '&#xe9a2;',
		'gi-label2': '&#xe9a3;',
		'gi-undo': '&#xe9a4;',
		'gi-undo2': '&#xe9a5;',
		'gi-redo': '&#xe9a6;',
		'gi-redo2': '&#xe9a7;',
		'gi-resize-vertical': '&#xe9a8;',
		'gi-resize-vertical2': '&#xe9a9;',
		'gi-resize-horizontal': '&#xe9aa;',
		'gi-resize-horizontal2': '&#xe9ab;',
		'gi-expand': '&#xe9ac;',
		'gi-expand2': '&#xe9ad;',
		'gi-collapse': '&#xe9ae;',
		'gi-collapse2': '&#xe9af;',
		'gi-chevron-left': '&#xe9b0;',
		'gi-chevron-left2': '&#xe9b1;',
		'gi-chevron-right': '&#xe9b2;',
		'gi-chevron-right2': '&#xe9b3;',
		'gi-chevron-up': '&#xe9b4;',
		'gi-chevron-up2': '&#xe9b5;',
		'gi-chevron-down': '&#xe9b6;',
		'gi-chevron-down2': '&#xe9b7;',
		'gi-logo-pc': '&#xe9b8;',
		'gi-logo': '&#xe9b9;',
		'gi-accomdation': '&#xe9ba;',
		'gi-alarm': '&#xe9bb;',
		'gi-arrow-down': '&#xe9bc;',
		'gi-arrow-right': '&#xe9bd;',
		'gi-bus': '&#xe9be;',
		'gi-cart': '&#xe9bf;',
		'gi-category': '&#xe9c0;',
		'gi-close': '&#xe9c1;',
		'gi-home': '&#xe9c2;',
		'gi-jeju': '&#xe9c3;',
		'gi-local': '&#xe9c4;',
		'gi-my-coupon': '&#xe9c5;',
		'gi-my-menu': '&#xe9c6;',
		'gi-my-review': '&#xe9c7;',
		'gi-order-list': '&#xe9c8;',
		'gi-real_qna': '&#xe9c9;',
		'gi-search': '&#xe9ca;',
		'gi-ticket': '&#xe9cb;',
		'gi-zeropass': '&#xe9cc;',
		'gi-wishlist': '&#xe9cd;',
		'0': 0
		},
		els = document.getElementsByTagName('*'),
		i, c, el;
	for (i = 0; ; i += 1) {
		el = els[i];
		if(!el) {
			break;
		}
		c = el.className;
		c = c.match(/gi-[^\s'"]+/);
		if (c && icons[c[0]]) {
			addIcon(el, icons[c[0]]);
		}
	}
}());
